package k8s

import (
	"context"
	"fmt"
	"time"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/apimachinery/pkg/util/wait"
	"k8s.io/client-go/kubernetes"
)

const (
	defaultKataRuntime  = "kata-qemu"
	defaultPriorityNorm = "tenant-normal"
	defaultPriorityLow  = "tenant-low"
)

// Config holds k8s client configuration
type Config struct {
	KataRuntimeClass string
	OpenClawImage    string
	S3Bucket         string
	S3Region         string
	RouterPublicURL  string
}

// Client wraps kubernetes.Interface with tenant-specific helpers
type Client struct {
	cs  kubernetes.Interface
	cfg Config
}

func New(cs kubernetes.Interface, cfg Config) *Client {
	if cfg.KataRuntimeClass == "" {
		cfg.KataRuntimeClass = defaultKataRuntime
	}
	return &Client{cs: cs, cfg: cfg}
}

// CreateTenantPod creates the OpenClaw pod for a tenant.
// If nodeName is non-empty, the pod is pinned to that node (used when
// assigning from a warm pool pod to skip Karpenter provisioning).
func (c *Client) CreateTenantPod(ctx context.Context, tenantID, namespace, botToken, hooksToken, webhookSecret, nodeName string) (*corev1.Pod, error) {
	podName := podName(tenantID)
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      podName,
			Namespace: namespace,
			Labels: map[string]string{
				"app":    "openclaw",
				"tenant": tenantID,
			},
		},
		Spec: corev1.PodSpec{
			RuntimeClassName:   strPtr(c.cfg.KataRuntimeClass),
			PriorityClassName:  defaultPriorityNorm,
			ServiceAccountName: "openclaw-tenant",
			NodeName:           nodeName, // pin to warm node if provided
			NodeSelector: map[string]string{
				"katacontainers.io/kata-runtime": "true",
			},
			Tolerations: []corev1.Toleration{
				{
					Key:      "kata-runtime",
					Value:    "true",
					Operator: corev1.TolerationOpEqual,
					Effect:   corev1.TaintEffectNoSchedule,
				},
			},
			// Lazy init: restore state + workspace from S3 before openclaw starts
			InitContainers: []corev1.Container{
				{
					// Restore .openclaw/ state and workspace/ from S3 via aws cli.
					// Prefixes derived from TENANT_ID: tenants/${TENANT_ID}/state|workspace/
					// openclaw.json is excluded — always regenerated by openclaw-start.sh.
					Name:  "s3-restore",
					Image: "public.ecr.aws/aws-cli/aws-cli:2.15.30",
					Command: []string{"sh", "-c",
						"STATE=s3://${S3_BUCKET}/tenants/${TENANT_ID}/state/; " +
							"WORK=s3://${S3_BUCKET}/tenants/${TENANT_ID}/workspace/; " +
							"echo \"[s3-restore] state  ${STATE} → /openclaw-state/\"; " +
							"aws s3 sync ${STATE} /openclaw-state/ " +
							"  --exclude 'openclaw.json' --exclude 'openclaw.json.*' " +
							"  --exclude '*.lock' " +
							"  --region ${AWS_REGION} 2>&1 " +
							"  && echo '[s3-restore] state OK' || echo '[s3-restore] state FAIL/empty'; " +
							"echo \"[s3-restore] workspace ${WORK} → /workspace/\"; " +
							"aws s3 sync ${WORK} /workspace/ " +
							"  --exclude '*/.workspace-state.json.*' --exclude '*/workspace-state.json.tmp-*' --exclude '.workspace-state.json.*' --exclude 'workspace-state.json.tmp-*' " +
							"  --region ${AWS_REGION} 2>&1 " +
							"  && echo '[s3-restore] workspace OK' || echo '[s3-restore] workspace FAIL/empty'; " +
							"echo '[s3-restore] Done.'",
					},
					Env: []corev1.EnvVar{
						{Name: "TENANT_ID", Value: tenantID},
						{Name: "S3_BUCKET", Value: c.cfg.S3Bucket},
						{Name: "AWS_REGION", Value: c.cfg.S3Region},
					},
					VolumeMounts: []corev1.VolumeMount{
						{Name: "openclaw-state", MountPath: "/openclaw-state"},
						{Name: "workspace", MountPath: "/workspace"},
					},
				},
			},
			Containers: []corev1.Container{
				{
					Name:            "openclaw",
					Image:           c.cfg.OpenClawImage,
					ImagePullPolicy: corev1.PullAlways,
					Env: []corev1.EnvVar{
						{Name: "TENANT_ID", Value: tenantID},
						{Name: "TELEGRAM_BOT_TOKEN", Value: botToken},
						{Name: "OPENCLAW_HOOKS_TOKEN", Value: hooksToken},
						{Name: "TELEGRAM_WEBHOOK_SECRET", Value: webhookSecret},
						{Name: "ROUTER_PUBLIC_URL", Value: c.cfg.RouterPublicURL},
					},
					Resources: corev1.ResourceRequirements{
						Requests: corev1.ResourceList{
							corev1.ResourceCPU:    resource.MustParse("200m"),
							corev1.ResourceMemory: resource.MustParse("1Gi"),
						},
						Limits: corev1.ResourceList{
							corev1.ResourceCPU:    resource.MustParse("1000m"),
							corev1.ResourceMemory: resource.MustParse("2Gi"),
						},
					},
					ReadinessProbe: &corev1.Probe{
						ProbeHandler: corev1.ProbeHandler{
							TCPSocket: &corev1.TCPSocketAction{
								Port: intstrFromInt(8787),
							},
						},
						InitialDelaySeconds: 25,
						PeriodSeconds:       3,
						FailureThreshold:    40, // 120s total — gateway ~34s + webhook ~5s
					},
					VolumeMounts: []corev1.VolumeMount{
						{Name: "openclaw-state", MountPath: "/root/.openclaw"},
						{Name: "workspace", MountPath: "/openclaw-workspace"},
						{Name: "config-template", MountPath: "/etc/openclaw", ReadOnly: true},
					},
				},
				{
					// s3-sync sidecar: periodic backup emptyDir → S3 via aws s3 sync.
					// Sync logic lives in /scripts/s3-sync.sh (mounted from openclaw-sync-script ConfigMap)
					// so both the periodic loop and the PreStop hook share the same implementation.
					// Runs every 60s. PreStop hook handles final sync before SIGTERM.
					Name:  "s3-sync",
					Image: "public.ecr.aws/aws-cli/aws-cli:2.15.30",
					Command: []string{"sh", "-c",
						"ts() { date -u '+%Y-%m-%dT%H:%M:%SZ'; }; " +
							"log() { echo \"$(ts) [s3-sync] $*\"; }; " +
							"trap 'log \"SIGTERM received, PreStop handles final sync\"; exit 0' TERM INT; " +
							"log \"Starting (interval: 60s) bucket=${S3_BUCKET} tenant=${TENANT_ID}\"; " +
							"/scripts/s3-sync.sh; " +
							"while true; do sleep 60 & wait $!; /scripts/s3-sync.sh; done",
					},
					Lifecycle: &corev1.Lifecycle{
						PreStop: &corev1.LifecycleHandler{
							Exec: &corev1.ExecAction{
								Command: []string{"/scripts/s3-sync.sh"},
							},
						},
					},
					Env: []corev1.EnvVar{
						{Name: "TENANT_ID", Value: tenantID},
						{Name: "S3_BUCKET", Value: c.cfg.S3Bucket},
						{Name: "AWS_REGION", Value: c.cfg.S3Region},
					},
					VolumeMounts: []corev1.VolumeMount{
						{Name: "openclaw-state", MountPath: "/openclaw-state"},
						{Name: "workspace", MountPath: "/workspace"},
						{Name: "sync-script", MountPath: "/scripts", ReadOnly: true},
					},
				},
			},
			Volumes: []corev1.Volume{
				{
					// openclaw-state: emptyDir for /root/.openclaw — supports atomic writes
					Name:         "openclaw-state",
					VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}},
				},
				{
					// workspace: emptyDir for agent workspace — supports atomic writes
					Name:         "workspace",
					VolumeSource: corev1.VolumeSource{EmptyDir: &corev1.EmptyDirVolumeSource{}},
				},
				{
					// config-template: ConfigMap with openclaw.json.tpl
					// envsubst renders it at startup with pod env vars
					Name: "config-template",
					VolumeSource: corev1.VolumeSource{
						ConfigMap: &corev1.ConfigMapVolumeSource{
							LocalObjectReference: corev1.LocalObjectReference{
								Name: "openclaw-config-template",
							},
						},
					},
				},
				{
					// sync-script: ConfigMap with s3-sync.sh, shared by periodic loop and PreStop hook
					Name: "sync-script",
					VolumeSource: corev1.VolumeSource{
						ConfigMap: &corev1.ConfigMapVolumeSource{
							LocalObjectReference: corev1.LocalObjectReference{
								Name: "openclaw-sync-script",
							},
							DefaultMode: int32Ptr(0755),
						},
					},
				},
			},
			TerminationGracePeriodSeconds: int64Ptr(120),
		},
	}

	created, err := c.cs.CoreV1().Pods(namespace).Create(ctx, pod, metav1.CreateOptions{})
	if errors.IsAlreadyExists(err) {
		return c.cs.CoreV1().Pods(namespace).Get(ctx, podName, metav1.GetOptions{})
	}
	return created, err
}

// WaitPodReady polls until the pod is Running and has a PodIP, returns the IP
func (c *Client) WaitPodReady(ctx context.Context, tenantID, namespace string, timeout time.Duration) (string, error) {
	name := podName(tenantID)
	var podIP string
	err := wait.PollUntilContextTimeout(ctx, 2*time.Second, timeout, true, func(ctx context.Context) (bool, error) {
		pod, err := c.cs.CoreV1().Pods(namespace).Get(ctx, name, metav1.GetOptions{})
		if err != nil {
			return false, nil
		}
		if pod.Status.Phase == corev1.PodRunning && pod.Status.PodIP != "" {
			podIP = pod.Status.PodIP
			return true, nil
		}
		return false, nil
	})
	if err != nil {
		return "", fmt.Errorf("pod %s not ready after %s: %w", name, timeout, err)
	}
	return podIP, nil
}

// DeletePod deletes a pod with the given grace period
func (c *Client) DeletePod(ctx context.Context, podName, namespace string, gracePeriod int64) error {
	err := c.cs.CoreV1().Pods(namespace).Delete(ctx, podName, metav1.DeleteOptions{
		GracePeriodSeconds: &gracePeriod,
	})
	if errors.IsNotFound(err) {
		return nil
	}
	return err
}

// EnsureWarmPoolDeployment creates or updates the warm-pool Deployment to the desired replica count.
// Warm pods run the real OpenClaw image at low priority with label warm=true.
// When a warm pod is consumed by a tenant, call GetWarmPod to detach it from the Deployment.
func (c *Client) EnsureWarmPoolDeployment(ctx context.Context, namespace string, replicas int32) error {
	const name = "warm-pool"
	labels := map[string]string{
		"app":  "warm-pool",
		"warm": "true",
	}

	podSpec := corev1.PodSpec{
		RuntimeClassName:   strPtr(c.cfg.KataRuntimeClass),
		PriorityClassName:  defaultPriorityLow,
		ServiceAccountName: "openclaw-tenant",
		NodeSelector: map[string]string{
			"katacontainers.io/kata-runtime": "true",
		},
		Tolerations: []corev1.Toleration{
			{
				Key:      "kata-runtime",
				Value:    "true",
				Operator: corev1.TolerationOpEqual,
				Effect:   corev1.TaintEffectNoSchedule,
			},
		},
		Containers: []corev1.Container{
			{
				// Warm pod purpose:
				//   1. Pull the openclaw image onto the node (so tenant pods start faster)
				//   2. Hold the node so Karpenter doesn't reclaim it
				// No gateway or Telegram — just sleep. Real work starts when GetWarmPod()
				// detaches this pod and the tenant pod is created on the same node.
				Name:            "openclaw",
				Image:           c.cfg.OpenClawImage,
				ImagePullPolicy: corev1.PullAlways,
				Command:         []string{"sleep", "infinity"},
				Resources: corev1.ResourceRequirements{
					Requests: corev1.ResourceList{
						corev1.ResourceCPU:    resource.MustParse("200m"),
						corev1.ResourceMemory: resource.MustParse("1Gi"),
					},
					Limits: corev1.ResourceList{
						corev1.ResourceCPU:    resource.MustParse("1000m"),
						corev1.ResourceMemory: resource.MustParse("2Gi"),
					},
				},
			},
		},
		TerminationGracePeriodSeconds: int64Ptr(10),
	}

	deploy := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: namespace,
			Labels:    labels,
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &replicas,
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app":  "warm-pool",
					"warm": "true",
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: labels},
				Spec:       podSpec,
			},
		},
	}

	existing, err := c.cs.AppsV1().Deployments(namespace).Get(ctx, name, metav1.GetOptions{})
	if errors.IsNotFound(err) {
		_, err = c.cs.AppsV1().Deployments(namespace).Create(ctx, deploy, metav1.CreateOptions{})
		return err
	}
	if err != nil {
		return err
	}

	// Update replicas and image if changed
	existing.Spec.Replicas = &replicas
	existing.Spec.Template.Spec.Containers[0].Image = c.cfg.OpenClawImage
	_, err = c.cs.AppsV1().Deployments(namespace).Update(ctx, existing, metav1.UpdateOptions{})
	return err
}

// ScaleWarmPool sets the warm-pool Deployment replica count.
func (c *Client) ScaleWarmPool(ctx context.Context, namespace string, replicas int32) error {
	existing, err := c.cs.AppsV1().Deployments(namespace).Get(ctx, "warm-pool", metav1.GetOptions{})
	if err != nil {
		return err
	}
	existing.Spec.Replicas = &replicas
	_, err = c.cs.AppsV1().Deployments(namespace).Update(ctx, existing, metav1.UpdateOptions{})
	return err
}

// GetWarmPod finds a running warm pod and atomically detaches it from the
// Deployment by removing the "warm=true" label (so the Deployment no longer
// manages it). Returns nil if no warm pod is available.
func (c *Client) GetWarmPod(ctx context.Context, namespace string) (*corev1.Pod, error) {
	list, err := c.cs.CoreV1().Pods(namespace).List(ctx, metav1.ListOptions{
		LabelSelector: "app=warm-pool,warm=true",
	})
	if err != nil {
		return nil, err
	}
	for i := range list.Items {
		p := &list.Items[i]
		if p.Status.Phase != corev1.PodRunning ||
			p.Status.PodIP == "" ||
			p.DeletionTimestamp != nil {
			continue
		}
		// Detach from Deployment by changing warm=true → warm=consuming
		// The Deployment selector requires warm=true, so this pod is now orphaned.
		pCopy := p.DeepCopy()
		pCopy.Labels["warm"] = "consuming"
		updated, err := c.cs.CoreV1().Pods(namespace).Update(ctx, pCopy, metav1.UpdateOptions{})
		if err != nil {
			// Another orchestrator replica claimed this pod first — try the next one
			continue
		}
		return updated, nil
	}
	return nil, nil
}

// CountWarmPods returns the number of active (not being consumed) warm pool pods.
func (c *Client) CountWarmPods(ctx context.Context, namespace string) (int, error) {
	list, err := c.cs.CoreV1().Pods(namespace).List(ctx, metav1.ListOptions{
		LabelSelector: "app=warm-pool,warm=true",
	})
	if err != nil {
		return 0, err
	}
	count := 0
	for _, p := range list.Items {
		if p.Status.Phase != corev1.PodFailed && p.DeletionTimestamp == nil {
			count++
		}
	}
	return count, nil
}

// PodExists checks whether a pod with the given name exists in the namespace
func (c *Client) PodExists(ctx context.Context, name, namespace string) (bool, error) {
	_, err := c.cs.CoreV1().Pods(namespace).Get(ctx, name, metav1.GetOptions{})
	if err != nil {
		if errors.IsNotFound(err) {
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// GetPodIP returns the current IP of a running pod, or "" if not ready.
func (c *Client) GetPodIP(ctx context.Context, name, namespace string) (string, error) {
	pod, err := c.cs.CoreV1().Pods(namespace).Get(ctx, name, metav1.GetOptions{})
	if err != nil {
		if errors.IsNotFound(err) {
			return "", nil
		}
		return "", err
	}
	if pod.Status.Phase == corev1.PodRunning && pod.Status.PodIP != "" {
		return pod.Status.PodIP, nil
	}
	return "", nil
}

// TenantPodInfo holds info about a tenant pod for reconciliation and orphan detection.
type TenantPodInfo struct {
	Name      string
	IP        string
	Phase     corev1.PodPhase
	CreatedAt time.Time
}

// ListTenantPods returns info about all tenant pods in the namespace.
func (c *Client) ListTenantPods(ctx context.Context, namespace string) ([]TenantPodInfo, error) {
	list, err := c.cs.CoreV1().Pods(namespace).List(ctx, metav1.ListOptions{
		LabelSelector: "app=openclaw",
	})
	if err != nil {
		return nil, err
	}
	pods := make([]TenantPodInfo, 0, len(list.Items))
	for _, p := range list.Items {
		pods = append(pods, TenantPodInfo{
			Name:      p.Name,
			IP:        p.Status.PodIP,
			Phase:     p.Status.Phase,
			CreatedAt: p.CreationTimestamp.Time,
		})
	}
	return pods, nil
}

// Helpers
func podName(tenantID string) string { return tenantID }
func strPtr(s string) *string        { return &s }
func int32Ptr(i int32) *int32        { return &i }
func int64Ptr(i int64) *int64        { return &i }

// intstrFromInt wraps an int as IntOrString (used for probe port)
func intstrFromInt(i int) intstr.IntOrString {
	return intstr.FromInt32(int32(i))
}
